### ISSUE TITLE
Sum of CLOCK intervals in the subtree just for today

### ISSUE THREAD

**Issue by qingbyin** [gsingh93/org-custom-cookies#5]
Hi,
Awesome work! I have just one question. Because I have some repeated tasks, I find the `[C:]` will sum up all days clock intervals.
My question is can I custom it so that it will only sum up clock intervals  like the `%CLOCKSUM_T` option in the org column view.

**Comment by gsingh93** [comment]
Hi,

Could you give an example org file with the `[C:]`, and what you want it to look like afterwards?

**Comment by qingbyin** [comment]
Sure. For example, I review my Anki cards every day. I want the [C:] cookie shows [C:28] (for today) instead of [C:1:54}] ( for all repeated days)
```
*** TODO Review Anki [E: 0:30] [C: 1:54]    ;;;;;;;  Prefer  [C:0:28]
SCHEDULED: <2022-10-29 Sat .+1d>
:PROPERTIES:
:STYLE: habit
:Effort:   30min
:LAST_REPEAT: [2022-10-28 Fri 23:49]
:END:
:LOGBOOK:
CLOCK: [2022-10-30 Sun 11:22]--[2022-10-30 Sun 11:50] =>  0:28
- State "DONE"       from "TODO"       [2022-10-28 Fri 23:49]
CLOCK: [2022-10-28 Fri 23:02]--[2022-10-28 Fri 23:48] =>  0:46
CLOCK: [2022-10-28 Fri 19:30]--[2022-10-28 Fri 20:10] =>  0:40
:END:
```

Setting %CLOCKSUM_T option can achieve this in the org column view:
![image](https://user-images.githubusercontent.com/50772432/198862178-72e472c2-6a5a-4f29-8414-a18c42521e52.png)

**Comment by gsingh93** [comment]
Thanks for the example!

Currently the code is computing `CLOCKSUM` using the method `org-clock-sum` here: https://github.com/gsingh93/org-custom-cookies/blob/main/org-custom-cookies.el#L87

To get `CLOCKSUM_T`, which is the clock sum for today, it needs to be changed to `org-clock-sum-today`. I wouldn't mind this being included in the library, but I don't have the time to add it along with tests and documentation right now. So I'd recommend you just patch this locally, or if you're comfortable writing elisp, create your own function that does this (just copying and pasting the original one and change the method), and add it to `org-custom-cookies-alist`, as specified in the README).

Let me know if you run into any trouble with this.

**Comment by qingbyin** [comment]
Thank you for your instruction, but I followed it and it seems to be not working. I get 0:00 clock sum for all entries.
```
*** TODO Review Anki [E: 0:30] [C: 0:00]
```
```lisp
(defun org-clocksum-today-cookie ()
  "Return the clocksum of a subtree as a cookie string."
  (progn
    ;; `org-clock-sum' computes the CLOCKSUM property of all headings in minutes
    ;; and stores it in the :org-clock-minutes property of the heading
    (org-clock-sum-today)
    ;; If this heading has a clock sum, return it, otherwise return zero
    (format "[C: %s]" (org-duration-from-minutes
                       (or (get-text-property (point) :org-clock-minutes) 0)))))
 (setq org-custom-cookies-alist
   '(("\\[S: ?\\(?:[0-9]*:[0-9]*\\)?\\]" . org-custom-cookies--subtree-scheduled-duration-cookie)
     ("\\[C: ?\\(?:[0-9]*:[0-9]*\\)?\\]" . org-clocksum-today-cookie)
     ("\\[E: ?\\(?:[0-9]*:[0-9]*\\)?\\]" . org-custom-cookies--subtree-effort-cookie)))
```

**Comment by gsingh93** [comment]
Hi, sorry about the long delay here. This will do what you want:
```elisp
(defun org-custom-cookies--subtree-clocksum-t-cookie ()
  "Return the clocksum for today of a subtree as a cookie string."
  (progn
    (org-clock-sum)
    (format "[C: %s]" (org-duration-from-minutes
                       ;; Not sure if the `or' is needed here
                       (or (org-clock-sum-today) 0)))))
```

Going to close this now, but feel free to reopen if this doesn't work.
